---
trigger:
- feature*

pool:
  vmImage: ubuntu-16.04

steps:

- checkout: git://kulsharm2/role-name
  path: role-name

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: python -m pip install "molecule[lint]" "python-docker" "molecule-docker" "ansible"
  displayName: Install dependencies

- script: python -m pip install "python-tss-sdk"
  displayName: Role-specific dependencies

- script: |
    export PATH="$PATH:/home/<user>/.local/bin/"
    cd $(Agent.BuildDirectory)/role-name
    molecule test
  displayName: Test relevant platforms